config/routes.rb
Rails.application.routes.draw do
  root 'public#welcome'

  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  get 'public/about'
  get 'public/search'
  get 'public/status'
  get 'public/welcome'

  get 'public/article/:id', to: 'public#article'

  get 'api/bibliography'
  get 'api/status_counts'

  resources :articles
  resources :issues
  resources :magazines
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commodore 8-Bit Magazine Index</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", as: "style" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <header>
      <div class="header-left">
        <%= link_to (user_signed_in? ? public_welcome_path : root_path) do %>
          <%= image_tag('cbmmag_logo.png', alt: 'CBM Magazine Index', class: 'cbm-logo') %>
        <% end %>
      </div>
      <div class="header-right">
        <% if user_signed_in? %>
          <nav class="nav-menu" id="admin-nav">
            <%= link_to 'Articles', articles_path, class: 'navbar-link' %>|
            <%= link_to 'Issues', issues_path, class: 'navbar-link' %>|
            <%= link_to 'Magazines', magazines_path, class: 'navbar-link' %>
        </nav>
        <% end %>
        <nav class="nav-menu" id="public-nav">
          <%= link_to 'Home', public_welcome_path %>|
          <%= link_to 'Search', public_search_path %>|
          <%= link_to 'Status', public_status_path %>|
          <%= link_to 'About', public_about_path %>
        </nav>
      </div>
    </header>

    <div class="layout-bar bar-red"></div>
    <div class="layout-bar bar-orange"></div>
    <div class="layout-bar bar-yellow"></div>
    <div class="layout-bar bar-green"></div>
    <div class="layout-bar bar-blue"></div>

    <section id="title-bar">
      <div id="title-content">
        <% if yield(:title).present? %>
          <h1 id="page-title"><%= yield(:title) %></h1>
        <% end %>
      </div>
    </section>

    <%= turbo_frame_tag 'modal', class: 'article-details' %>
    <%= yield %>

    <footer>
      <%= tag.span do %>
        Commodore 8-Bit Magazine Index v2.0&ndash; Copyright &copy; <%= Time.now.year %> Myles L. Skinner &ndash; All Rights Reserved.
      <% end %>
      <span class="admin-login">
        <% if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'footer-login-link' %>
        <% else %>
          <%= link_to 'Admin Login', new_session_path('user'), class: 'footer-login-link' %>
        <% end %>
      </span>
    </footer>
  </body>
</html>